### ISSUE TITLE
How to build ISP Tool

### ISSUE THREAD

**Issue by DaoThanhLong** [OpenNuvoton/ISPTool#1]
Hi 
I want to rebuild ISP Tool by my side.
However, I can't find guilder line.
Please help me.
My OS : Window
Thank you so much.

**Comment by JCSTwo** [comment]
Hi,

This tool is developed by Microsoft Visual Studio.
And there are two .sln files (Microsoft Visual Studio Solution File) included in this project
which can be found in "OpenNuvoton/ISPTool/NuvoISP/".
NuvoISP_VS2008.sln is for Visaul Studio 2008.
NuvoISP_VS2010.sln is for Visaul Studio 201x.

Sincerely,

CCTu.

**Comment by DaoThanhLong** [comment]
Hi,
Thank for your help.
