### ISSUE TITLE
Documentation on ICP Protocol for 8051

### ISSUE THREAD

**Issue by ChristianRinn** [OpenNuvoton/ISPTool#2]
There does not seem to be any information about the ISP protocol available, neither in the datasheets nor in any other document. Is there any plan to release such information or do we have to reverse engineer the protocol from the ISP tool?

**Comment by JCSTwo** [comment]
Hi ChristianRinn ,

There is one application note for ISP protocol.
But I can't find the download link now.
I have forwarded this information to the 8051 ISP owner Lucia.

You may contact her via E-Mail to get further support. --> LCWANG0@nuvoton.com

Sincerely,
CCTu

**Comment by ChristianRinn** [comment]
Hi CCTu,

Thank you for the quick answer. I'm very sorry but I accidentally said ISP protocol but I meant the ICP protocol which is used by the Nulink to program a non-Cortex-M device such as the N76E003.

**Comment by JCSTwo** [comment]
Hi ChristianRinn,

You can contact Lucia for any problem about 8051 product line.
Lucia can answer your question or forward to related colleague.
Since this is not an issue for ISP, so I'll switch this issue status to close.

Sincerely,
CCTu

**Comment by buttim** [comment]
Any news on this?
